function [pCorrect, confusionMatrix] = evaluateClassifier(k, size, italic, bold, multipleFonts, evaluateFinal)
%[pCorrect, confusionMatrix] = evaluateClassifier(k, size, italic, bold, multipleFonts, evaluateFinal)

type = 'Train';

testingGlyphs = loadGlyphs(...
    'C:\Users\David\OneDrive\Master''s Year 1\CSIC 859\Classifer Project\My Digits',...
    type, size, italic, bold, multipleFonts);

testingGlyphs = extractFeatures(testingGlyphs);

if evaluateFinal
    type = 'Test';
    
    moreTestingGlyphs = loadGlyphs(...
        'C:\Users\David\OneDrive\Master''s Year 1\CSIC 859\Classifer Project\My Digits',...
        type, size, italic, bold, multipleFonts);
    
    moreTestingGlyphs = extractFeatures(moreTestingGlyphs);
    
    testingGlyphs = [testingGlyphs; moreTestingGlyphs];
end

features = [...
    Features.aspectRatio,...
    Features.holesAreaRatio,...
    Features.holesAreaTop,...
    Features.holesAreaBottom,...
    Features.subtractedVerticalSymmetry,...
    Features.subtractedHorizontalSymmetry,...
    Features.verticalSymmetry,...
    Features.horizontalSymmetry,...
    Features.topRightBottomLeftSymmetry,...
    Features.topLeftBottomRightSymmetry,...
    Features.leftSideContourVariance,...
    Features.rightSideContourVariance,...
    Features.totalContourVariance,...
    Features.contourVarianceSymmetry,...
    Features.widthAtTop,...
    Features.widthAtBottom,...
    Features.widthAtMiddle,...
    Features.perimeterRatio,...
    Features.maximumDepthFromLeftTop,...
    Features.maximumDepthFromRightTop,...
    Features.maximumDepthFromLeftBottom,...
    Features.maximumDepthFromRightBottom...
    ];

features = features(true & [1 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1]);

classifier = NearestNeighbour(testingGlyphs, k, features);

% CLASSIFY TESTING SET

size = true;
italic = true;
bold = true;

if evaluateFinal
    type = 'Final';
else
    type = 'Test';
end

testingGlyphs = loadGlyphs(...
    'C:\Users\David\OneDrive\Master''s Year 1\CSIC 859\Classifer Project\My Digits',...
    type, size, italic, bold, multipleFonts);

testingGlyphs = extractFeatures(testingGlyphs);

testingGlyphs = classifier.classifyGlyphs(testingGlyphs, features);

classes = [...
    Classes.zero,...
    Classes.one,...
    Classes.two,...
    Classes.three,...
    Classes.four,...
    Classes.five,...
    Classes.six,...
    Classes.seven,...
    Classes.eight,...
    Classes.nine...
    ];

[pCorrect, confusionMatrix] = analyzeClassification(testingGlyphs, classes);

end

% HELPER FUNCTIONS
function glyphs = extractFeatures(glyphs)

numGlyphs = length(glyphs);

parfor i=1:numGlyphs
    glyphs{i} = glyphs{i}.extractAndSetFeatures();
end

end
