function [] = testClassification()
%[] = testClassification()

size = true;
italic = true;
bold = true;

type = 'Train';

testingGlyphs = loadGlyphs(...
    'C:\Users\David\OneDrive\Master''s Year 1\CSIC 859\Classifer Project\My Digits\Multiple Fonts Glyphs\',...
    type, size, italic, bold);

testingGlyphs = extractFeatures(testingGlyphs);



features = [...
    Features.aspectRatio,...
    Features.holesAreaRatio,...
    Features.holesAreaTop,...
    Features.holesAreaBottom,...
    Features.subtractedVerticalSymmetry,...
    Features.subtractedHorizontalSymmetry,...
    Features.verticalSymmetry,...
    Features.horizontalSymmetry,...
    Features.topRightBottomLeftSymmetry,...
    Features.topLeftBottomRightSymmetry,...
    Features.leftSideContourVariance,...
    Features.rightSideContourVariance,...
    Features.totalContourVariance,...
    Features.contourVarianceSymmetry,...
    Features.widthAtTop,...
    Features.widthAtBottom,...
    Features.widthAtMiddle,...
    Features.perimeterRatio...
    ];

features = features(true & [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]);

k = 1;

classifier = NearestNeighbour(testingGlyphs, k, features);

% CLASSIFY TESTING SET

size = true;
italic = true;
bold = true;

type = 'Test';

testingGlyphs = loadGlyphs(...
    'C:\Users\David\OneDrive\Master''s Year 1\CSIC 859\Classifer Project\My Digits\Multiple Fonts Glyphs\',...
    type, size, italic, bold);

testingGlyphs = extractFeatures(testingGlyphs);

testingGlyphs = classifier.classifyGlyphs(testingGlyphs, features);

classes = [...
    Classes.zero,...
    Classes.one,...
    Classes.two,...
    Classes.three,...
    Classes.four,...
    Classes.five,...
    Classes.six,...
    Classes.seven,...
    Classes.eight,...
    Classes.nine...
    ];

[pCorrect, confusionMatrix] = analyzeClassification(testingGlyphs, classes);

disp(['%: ', num2str(pCorrect)]);
disp(confusionMatrix);
end

% HELPER FUNCTIONS
function glyphs = extractFeatures(glyphs)

numGlyphs = length(glyphs);

parfor i=1:numGlyphs
    glyphs{i} = glyphs{i}.extractAndSetFeatures();
end

end
